version: '3.9'

services:
  messaging-app-db:
    container_name: messaging-app-db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5434:5432
    env_file: ./src/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
