# Deploy

name: socialbe-deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish Latest to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: KATITB22/Social-BE/production
          username: ${{ secrets.PKG_REGISTRY_USERNAME }}
          password: ${{ secrets.PKG_REGISTRY_PASSWORD }}
          registry: docker.pkg.github.com
          tags: 'latest'
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ADIUTOR_HOST }}
          port: 22
          username: ${{ secrets.ADIUTOR_USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd adiutor
            docker-compose pull
            docker-compose up -d --remove-orphans
            docker image prune -f
